// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BlueprintDTO {
    "name": string;
    "description": string;
    "fileName": string;
    "charts": ChartEntryDTO[];

    /** Creates a new BlueprintDTO instance. */
    constructor($$source: Partial<BlueprintDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("charts" in $$source)) {
            this["charts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlueprintDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BlueprintDTO {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("charts" in $$parsedSource) {
            $$parsedSource["charts"] = $$createField3_0($$parsedSource["charts"]);
        }
        return new BlueprintDTO($$parsedSource as Partial<BlueprintDTO>);
    }
}

export class BlueprintDeployRequest {
    "blueprintName": string;
    "clusterName": string;
    "namespace": string;

    /** Creates a new BlueprintDeployRequest instance. */
    constructor($$source: Partial<BlueprintDeployRequest> = {}) {
        if (!("blueprintName" in $$source)) {
            this["blueprintName"] = "";
        }
        if (!("clusterName" in $$source)) {
            this["clusterName"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlueprintDeployRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BlueprintDeployRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlueprintDeployRequest($$parsedSource as Partial<BlueprintDeployRequest>);
    }
}

export class BlueprintEventDTO {
    "name": string;
    "message": string;

    /** Creates a new BlueprintEventDTO instance. */
    constructor($$source: Partial<BlueprintEventDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlueprintEventDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BlueprintEventDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlueprintEventDTO($$parsedSource as Partial<BlueprintEventDTO>);
    }
}

export class ChartEntryDTO {
    "releaseName": string;
    "repo": string;
    "chart": string;
    "version": string;
    "values": string;

    /** Creates a new ChartEntryDTO instance. */
    constructor($$source: Partial<ChartEntryDTO> = {}) {
        if (!("releaseName" in $$source)) {
            this["releaseName"] = "";
        }
        if (!("repo" in $$source)) {
            this["repo"] = "";
        }
        if (!("chart" in $$source)) {
            this["chart"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("values" in $$source)) {
            this["values"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ChartEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChartEntryDTO($$parsedSource as Partial<ChartEntryDTO>);
    }
}

/**
 * ClusterCreateAdvancedRequest covers all configurable aspects of k3d cluster create.
 */
export class ClusterCreateAdvancedRequest {
    "name": string;

    /**
     * Topology
     */
    "servers": number;
    "agents": number;
    "image": string;

    /**
     * API exposure
     */
    "apiPort": string;
    "apiHost": string;
    "apiHostIP": string;

    /**
     * Networking
     */
    "network": string;
    "subnet": string;
    "token": string;

    /**
     * Resource limits
     */
    "serversMemory": string;
    "agentsMemory": string;
    "gpuRequest": string;

    /**
     * Port mappings  — "HOST:HOSTPORT:CONTAINERPORT/PROTO@nodefilter"
     */
    "ports": NodeFilter[];

    /**
     * Volume mounts — "source:dest@nodefilter"
     */
    "volumes": NodeFilter[];

    /**
     * Env vars — "KEY=VALUE@nodefilter"
     */
    "env": NodeFilter[];

    /**
     * k3s extra args — "arg@nodefilter"
     */
    "k3sArgs": NodeFilter[];

    /**
     * k3s node labels — "key=value@nodefilter"
     */
    "k3sNodeLabels": NodeFilter[];

    /**
     * Runtime labels — "key=value@nodefilter"
     */
    "runtimeLabels": NodeFilter[];

    /**
     * Registries
     * "name[:host][:port]"
     */
    "registryCreate": string;
    "registryUse": string[];

    /**
     * k3d behaviour flags
     */
    "noLoadbalancer": boolean;
    "noImageVolume": boolean;
    "noRollback": boolean;

    /**
     * options.k3d.timeout, e.g. "60s"
     */
    "timeout": string;

    /**
     * options.k3d.loadbalancer.configOverrides
     */
    "lbConfigOverrides": string[];

    /**
     * Runtime extras
     * options.runtime.hostPidMode
     */
    "hostPidMode": boolean;

    /**
     * options.runtime.ulimits
     */
    "ulimits": UlimitDTO[];

    /**
     * Files (injected into nodes)
     */
    "files": FileDTO[];

    /**
     * Host aliases (/etc/hosts injections)
     */
    "hostAliases": HostAliasDTO[];

    /**
     * Registry extras
     * registries.create.host
     */
    "registryCreateHost": string;

    /**
     * registries.create.hostPort
     */
    "registryCreatePort": string;

    /**
     * registries.create.proxy.remoteURL
     */
    "registryProxyURL": string;

    /**
     * registries.create.proxy.username
     */
    "registryProxyUser": string;

    /**
     * registries.create.proxy.password
     */
    "registryProxyPass": string;

    /**
     * registries.create.volumes
     */
    "registryVolumes": string[];

    /**
     * registries.config (inline YAML or path)
     */
    "registryConfig": string;

    /**
     * Kubeconfig
     */
    "updateKubeconfig": boolean;
    "switchContext": boolean;

    /** Creates a new ClusterCreateAdvancedRequest instance. */
    constructor($$source: Partial<ClusterCreateAdvancedRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("servers" in $$source)) {
            this["servers"] = 0;
        }
        if (!("agents" in $$source)) {
            this["agents"] = 0;
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("apiPort" in $$source)) {
            this["apiPort"] = "";
        }
        if (!("apiHost" in $$source)) {
            this["apiHost"] = "";
        }
        if (!("apiHostIP" in $$source)) {
            this["apiHostIP"] = "";
        }
        if (!("network" in $$source)) {
            this["network"] = "";
        }
        if (!("subnet" in $$source)) {
            this["subnet"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("serversMemory" in $$source)) {
            this["serversMemory"] = "";
        }
        if (!("agentsMemory" in $$source)) {
            this["agentsMemory"] = "";
        }
        if (!("gpuRequest" in $$source)) {
            this["gpuRequest"] = "";
        }
        if (!("ports" in $$source)) {
            this["ports"] = [];
        }
        if (!("volumes" in $$source)) {
            this["volumes"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = [];
        }
        if (!("k3sArgs" in $$source)) {
            this["k3sArgs"] = [];
        }
        if (!("k3sNodeLabels" in $$source)) {
            this["k3sNodeLabels"] = [];
        }
        if (!("runtimeLabels" in $$source)) {
            this["runtimeLabels"] = [];
        }
        if (!("registryCreate" in $$source)) {
            this["registryCreate"] = "";
        }
        if (!("registryUse" in $$source)) {
            this["registryUse"] = [];
        }
        if (!("noLoadbalancer" in $$source)) {
            this["noLoadbalancer"] = false;
        }
        if (!("noImageVolume" in $$source)) {
            this["noImageVolume"] = false;
        }
        if (!("noRollback" in $$source)) {
            this["noRollback"] = false;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = "";
        }
        if (!("lbConfigOverrides" in $$source)) {
            this["lbConfigOverrides"] = [];
        }
        if (!("hostPidMode" in $$source)) {
            this["hostPidMode"] = false;
        }
        if (!("ulimits" in $$source)) {
            this["ulimits"] = [];
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("hostAliases" in $$source)) {
            this["hostAliases"] = [];
        }
        if (!("registryCreateHost" in $$source)) {
            this["registryCreateHost"] = "";
        }
        if (!("registryCreatePort" in $$source)) {
            this["registryCreatePort"] = "";
        }
        if (!("registryProxyURL" in $$source)) {
            this["registryProxyURL"] = "";
        }
        if (!("registryProxyUser" in $$source)) {
            this["registryProxyUser"] = "";
        }
        if (!("registryProxyPass" in $$source)) {
            this["registryProxyPass"] = "";
        }
        if (!("registryVolumes" in $$source)) {
            this["registryVolumes"] = [];
        }
        if (!("registryConfig" in $$source)) {
            this["registryConfig"] = "";
        }
        if (!("updateKubeconfig" in $$source)) {
            this["updateKubeconfig"] = false;
        }
        if (!("switchContext" in $$source)) {
            this["switchContext"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterCreateAdvancedRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterCreateAdvancedRequest {
        const $$createField13_0 = $$createType3;
        const $$createField14_0 = $$createType3;
        const $$createField15_0 = $$createType3;
        const $$createField16_0 = $$createType3;
        const $$createField17_0 = $$createType3;
        const $$createField18_0 = $$createType3;
        const $$createField20_0 = $$createType4;
        const $$createField25_0 = $$createType4;
        const $$createField27_0 = $$createType6;
        const $$createField28_0 = $$createType8;
        const $$createField29_0 = $$createType10;
        const $$createField35_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField13_0($$parsedSource["ports"]);
        }
        if ("volumes" in $$parsedSource) {
            $$parsedSource["volumes"] = $$createField14_0($$parsedSource["volumes"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField15_0($$parsedSource["env"]);
        }
        if ("k3sArgs" in $$parsedSource) {
            $$parsedSource["k3sArgs"] = $$createField16_0($$parsedSource["k3sArgs"]);
        }
        if ("k3sNodeLabels" in $$parsedSource) {
            $$parsedSource["k3sNodeLabels"] = $$createField17_0($$parsedSource["k3sNodeLabels"]);
        }
        if ("runtimeLabels" in $$parsedSource) {
            $$parsedSource["runtimeLabels"] = $$createField18_0($$parsedSource["runtimeLabels"]);
        }
        if ("registryUse" in $$parsedSource) {
            $$parsedSource["registryUse"] = $$createField20_0($$parsedSource["registryUse"]);
        }
        if ("lbConfigOverrides" in $$parsedSource) {
            $$parsedSource["lbConfigOverrides"] = $$createField25_0($$parsedSource["lbConfigOverrides"]);
        }
        if ("ulimits" in $$parsedSource) {
            $$parsedSource["ulimits"] = $$createField27_0($$parsedSource["ulimits"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField28_0($$parsedSource["files"]);
        }
        if ("hostAliases" in $$parsedSource) {
            $$parsedSource["hostAliases"] = $$createField29_0($$parsedSource["hostAliases"]);
        }
        if ("registryVolumes" in $$parsedSource) {
            $$parsedSource["registryVolumes"] = $$createField35_0($$parsedSource["registryVolumes"]);
        }
        return new ClusterCreateAdvancedRequest($$parsedSource as Partial<ClusterCreateAdvancedRequest>);
    }
}

/**
 * ClusterCreateRequest is the simple (quick-create) form.
 */
export class ClusterCreateRequest {
    "name": string;
    "servers": number;
    "agents": number;

    /**
     * empty = default
     */
    "image": string;

    /**
     * empty = random
     */
    "apiPort": string;

    /** Creates a new ClusterCreateRequest instance. */
    constructor($$source: Partial<ClusterCreateRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("servers" in $$source)) {
            this["servers"] = 0;
        }
        if (!("agents" in $$source)) {
            this["agents"] = 0;
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("apiPort" in $$source)) {
            this["apiPort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterCreateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterCreateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterCreateRequest($$parsedSource as Partial<ClusterCreateRequest>);
    }
}

export class ClusterDTO {
    "name": string;
    "servers": number;
    "agents": number;

    /**
     * "running" | "stopped" | "partial"
     */
    "status": string;
    "nodes": NodeDTO[];
    "created": string;

    /** Creates a new ClusterDTO instance. */
    constructor($$source: Partial<ClusterDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("servers" in $$source)) {
            this["servers"] = 0;
        }
        if (!("agents" in $$source)) {
            this["agents"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterDTO {
        const $$createField4_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField4_0($$parsedSource["nodes"]);
        }
        return new ClusterDTO($$parsedSource as Partial<ClusterDTO>);
    }
}

export class FileDTO {
    "source": string;
    "destination": string;
    "description": string;

    /**
     * comma-separated
     */
    "nodeFilters": string;

    /** Creates a new FileDTO instance. */
    constructor($$source: Partial<FileDTO> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("nodeFilters" in $$source)) {
            this["nodeFilters"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): FileDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileDTO($$parsedSource as Partial<FileDTO>);
    }
}

export class HostAliasDTO {
    "ip": string;
    "hostnames": string[];

    /** Creates a new HostAliasDTO instance. */
    constructor($$source: Partial<HostAliasDTO> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("hostnames" in $$source)) {
            this["hostnames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostAliasDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HostAliasDTO {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hostnames" in $$parsedSource) {
            $$parsedSource["hostnames"] = $$createField1_0($$parsedSource["hostnames"]);
        }
        return new HostAliasDTO($$parsedSource as Partial<HostAliasDTO>);
    }
}

export class KubeconfigContextDTO {
    "name": string;
    "cluster": string;
    "user": string;
    "current": boolean;

    /** Creates a new KubeconfigContextDTO instance. */
    constructor($$source: Partial<KubeconfigContextDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeconfigContextDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): KubeconfigContextDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeconfigContextDTO($$parsedSource as Partial<KubeconfigContextDTO>);
    }
}

export class LogEntryDTO {
    "time": string;
    "level": string;
    "message": string;

    /**
     * "app" | "k3d"
     */
    "source": string;

    /**
     * cluster/node name this log belongs to, empty = unattributed
     */
    "target": string;

    /** Creates a new LogEntryDTO instance. */
    constructor($$source: Partial<LogEntryDTO> = {}) {
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntryDTO($$parsedSource as Partial<LogEntryDTO>);
    }
}

export class NodeDTO {
    "name": string;
    "role": string;
    "state": string;
    "image": string;

    /** Creates a new NodeDTO instance. */
    constructor($$source: Partial<NodeDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeDTO($$parsedSource as Partial<NodeDTO>);
    }
}

/**
 * NodeFilter pairs a value with an optional k3d node filter expression (e.g. "@server:0", "@agent:*").
 */
export class NodeFilter {
    "value": string;

    /**
     * single string, comma-separated filters
     */
    "nodeFilters": string;

    /** Creates a new NodeFilter instance. */
    constructor($$source: Partial<NodeFilter> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("nodeFilters" in $$source)) {
            this["nodeFilters"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeFilter($$parsedSource as Partial<NodeFilter>);
    }
}

export class ProfileDTO {
    /**
     * filename stem, e.g. "dev-cluster"
     */
    "name": string;

    /**
     * full filename, e.g. "dev-cluster.yaml"
     */
    "fileName": string;

    /** Creates a new ProfileDTO instance. */
    constructor($$source: Partial<ProfileDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileDTO($$parsedSource as Partial<ProfileDTO>);
    }
}

export class RegistryCreateRequest {
    "name": string;

    /**
     * 0 = random
     */
    "port": number;

    /** Creates a new RegistryCreateRequest instance. */
    constructor($$source: Partial<RegistryCreateRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistryCreateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistryCreateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegistryCreateRequest($$parsedSource as Partial<RegistryCreateRequest>);
    }
}

export class RegistryDTO {
    "name": string;
    "host": string;
    "port": number;
    "protocol": string;
    "state": string;

    /** Creates a new RegistryDTO instance. */
    constructor($$source: Partial<RegistryDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegistryDTO($$parsedSource as Partial<RegistryDTO>);
    }
}

export class UlimitDTO {
    "name": string;
    "soft": number;
    "hard": number;

    /** Creates a new UlimitDTO instance. */
    constructor($$source: Partial<UlimitDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("soft" in $$source)) {
            this["soft"] = 0;
        }
        if (!("hard" in $$source)) {
            this["hard"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UlimitDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): UlimitDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UlimitDTO($$parsedSource as Partial<UlimitDTO>);
    }
}

// Private type creation functions
const $$createType0 = ChartEntryDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = NodeFilter.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = UlimitDTO.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = FileDTO.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = HostAliasDTO.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = NodeDTO.createFrom;
const $$createType12 = $Create.Array($$createType11);
