// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

export function DeleteBlueprint(name: string): $CancellablePromise<void> {
    return $Call.ByID(4106361431, name);
}

export function DeployBlueprint(req: dto$0.BlueprintDeployRequest): $CancellablePromise<string> {
    return $Call.ByID(1831808911, req);
}

export function GetBlueprint(name: string): $CancellablePromise<dto$0.BlueprintDTO> {
    return $Call.ByID(727150356, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListBlueprints(): $CancellablePromise<dto$0.BlueprintDTO[]> {
    return $Call.ByID(2520973987).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveBlueprint(bp: dto$0.BlueprintDTO): $CancellablePromise<void> {
    return $Call.ByID(1145082445, bp);
}

// Private type creation functions
const $$createType0 = dto$0.BlueprintDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
