// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

export function CreateCluster(req: dto$0.ClusterCreateRequest): $CancellablePromise<void> {
    return $Call.ByID(1645023132, req);
}

export function CreateClusterAdvanced(req: dto$0.ClusterCreateAdvancedRequest): $CancellablePromise<void> {
    return $Call.ByID(3268881462, req);
}

export function DeleteCluster(name: string): $CancellablePromise<void> {
    return $Call.ByID(2212415657, name);
}

export function ListClusters(): $CancellablePromise<dto$0.ClusterDTO[]> {
    return $Call.ByID(488719565).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartCluster(name: string): $CancellablePromise<void> {
    return $Call.ByID(372684744, name);
}

export function StopCluster(name: string): $CancellablePromise<void> {
    return $Call.ByID(3867105232, name);
}

// Private type creation functions
const $$createType0 = dto$0.ClusterDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
