// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

/**
 * DeleteContext removes a context (and its cluster/user if exclusive) from ~/.kube/config.
 */
export function DeleteContext(contextName: string): $CancellablePromise<void> {
    return $Call.ByID(479841473, contextName);
}

/**
 * ExportKubeconfig merges cluster kubeconfig into ~/.kube/config and returns the path.
 * Kept synchronous because the frontend needs the returned path; wrapped with StartOp
 * so the operations store reflects in-flight state.
 */
export function ExportKubeconfig(clusterName: string): $CancellablePromise<string> {
    return $Call.ByID(4154605852, clusterName);
}

/**
 * GetKubeconfigYAML returns cluster kubeconfig as YAML string for display.
 */
export function GetKubeconfigYAML(clusterName: string): $CancellablePromise<string> {
    return $Call.ByID(4089147447, clusterName);
}

/**
 * ListContexts returns all contexts in ~/.kube/config.
 */
export function ListContexts(): $CancellablePromise<dto$0.KubeconfigContextDTO[]> {
    return $Call.ByID(2300217525).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetCurrentContext sets the active context in ~/.kube/config.
 */
export function SetCurrentContext(contextName: string): $CancellablePromise<void> {
    return $Call.ByID(3036994603, contextName);
}

// Private type creation functions
const $$createType0 = dto$0.KubeconfigContextDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
