// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService exposes log-level control and history to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

export function GetLevel(): $CancellablePromise<string> {
    return $Call.ByID(1897495804);
}

export function GetRecentLogs(): $CancellablePromise<dto$0.LogEntryDTO[]> {
    return $Call.ByID(71917350).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetLevel(level: string): $CancellablePromise<void> {
    return $Call.ByID(2065426928, level);
}

// Private type creation functions
const $$createType0 = dto$0.LogEntryDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
