// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

export function AddAgent(clusterName: string): $CancellablePromise<string> {
    return $Call.ByID(3684008734, clusterName);
}

export function DeleteNode(nodeName: string): $CancellablePromise<string> {
    return $Call.ByID(1159268401, nodeName);
}

export function ListNodes(clusterName: string): $CancellablePromise<dto$0.NodeDTO[]> {
    return $Call.ByID(3762438223, clusterName).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RestartNode(nodeName: string): $CancellablePromise<string> {
    return $Call.ByID(2181371209, nodeName);
}

export function StartNode(nodeName: string): $CancellablePromise<string> {
    return $Call.ByID(2040106362, nodeName);
}

export function StopNode(nodeName: string): $CancellablePromise<string> {
    return $Call.ByID(2625440930, nodeName);
}

export function UpgradeNode(nodeName: string, image: string): $CancellablePromise<string> {
    return $Call.ByID(1505253066, nodeName, image);
}

// Private type creation functions
const $$createType0 = dto$0.NodeDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
