// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OperationsService exposes the active-operation registry to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

/**
 * ListActive returns a snapshot of currently in-flight operations.
 * The frontend calls this at startup to rehydrate state after a window reload.
 * Returned entries have Phase = "start".
 */
export function ListActive(): $CancellablePromise<dto$0.OperationEventDTO[]> {
    return $Call.ByID(2210796342).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.OperationEventDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
