// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

/**
 * AdvancedRequestToYAML converts a ClusterCreateAdvancedRequest to a k3d v1alpha5 YAML string.
 */
export function AdvancedRequestToYAML(req: dto$0.ClusterCreateAdvancedRequest): $CancellablePromise<string> {
    return $Call.ByID(1525004250, req);
}

export function DeleteProfile(name: string): $CancellablePromise<void> {
    return $Call.ByID(2647709843, name);
}

export function GetProfile(name: string): $CancellablePromise<string> {
    return $Call.ByID(977747828, name);
}

/**
 * ImportProfile opens a file picker, copies the chosen YAML into the profiles dir,
 * and returns the stem name of the imported profile.
 */
export function ImportProfile(): $CancellablePromise<string> {
    return $Call.ByID(3478940053);
}

export function ListProfiles(): $CancellablePromise<dto$0.ProfileDTO[]> {
    return $Call.ByID(795445015).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveProfile validates the YAML (must unmarshal to SimpleConfig) then writes it.
 */
export function SaveProfile(name: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3511726857, name, content);
}

/**
 * YAMLToAdvancedRequest parses a k3d v1alpha5 YAML string into a ClusterCreateAdvancedRequest.
 */
export function YAMLToAdvancedRequest(content: string): $CancellablePromise<dto$0.ClusterCreateAdvancedRequest> {
    return $Call.ByID(2659638206, content).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.ProfileDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = dto$0.ClusterCreateAdvancedRequest.createFrom;
