// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../dto/models.js";

export function CreateRegistry(req: dto$0.RegistryCreateRequest): $CancellablePromise<void> {
    return $Call.ByID(2941490218, req);
}

export function DeleteRegistry(name: string): $CancellablePromise<void> {
    return $Call.ByID(1273757037, name);
}

export function ListRegistries(): $CancellablePromise<dto$0.RegistryDTO[]> {
    return $Call.ByID(3386377894).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.RegistryDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
