// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as dto$0 from "../../../../k3desktop/k3desktop/dto/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "blueprint:deploying": dto$0.BlueprintEventDTO;
            "blueprint:done": dto$0.BlueprintEventDTO;
            "blueprint:error": dto$0.BlueprintEventDTO;
            "cluster:creating": string;
            "cluster:error": string;
            "cluster:ready": string;
            "log:entry": dto$0.LogEntryDTO;
            "op:done": dto$0.OperationEventDTO;
            "op:error": dto$0.OperationEventDTO;
            "op:start": dto$0.OperationEventDTO;
        }
    }
}
