//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../../../k3desktop/k3desktop/dto/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "blueprint:deploying": $$createType0,
        "blueprint:done": $$createType0,
        "blueprint:error": $$createType0,
        "log:entry": $$createType1,
        "op:done": $$createType2,
        "op:error": $$createType2,
        "op:start": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = dto$0.BlueprintEventDTO.createFrom;
const $$createType1 = dto$0.LogEntryDTO.createFrom;
const $$createType2 = dto$0.OperationEventDTO.createFrom;

configure();
